name: Website Deployment
on:
  push:
    branches: '11ty-migration'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{secrets.GH_TOKEN}}

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: 16

    - name: Build Assets
      run: |
        yarn install
        yarn run build
        mv 404.md dist

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./dist
